// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260318164211_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LibraryApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mustafa Kemal Atatürk",
                            CategoryId = 3,
                            PageCount = 600,
                            PublishDate = new DateTime(1927, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nutuk"
                        },
                        new
                        {
                            Id = 2,
                            Author = "José Mauro de Vasconcelos",
                            CategoryId = 1,
                            PageCount = 182,
                            PublishDate = new DateTime(1968, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Şeker Portakalı"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Frank Herbert",
                            CategoryId = 2,
                            PageCount = 712,
                            PublishDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            CategoryId = 4,
                            PageCount = 464,
                            PublishDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Fyodor Dostoyevski",
                            CategoryId = 1,
                            PageCount = 687,
                            PublishDate = new DateTime(1866, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 6,
                            Author = "George Orwell",
                            CategoryId = 2,
                            PageCount = 328,
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Yuval Noah Harari",
                            CategoryId = 3,
                            PageCount = 412,
                            PublishDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Paulo Coelho",
                            CategoryId = 1,
                            PageCount = 188,
                            PublishDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Simyacı"
                        },
                        new
                        {
                            Id = 9,
                            Author = "James Clear",
                            CategoryId = 5,
                            PageCount = 320,
                            PublishDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Atomik Alışkanlıklar"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Sabahattin Ali",
                            CategoryId = 1,
                            PageCount = 160,
                            PublishDate = new DateTime(1943, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Oğuz Atay",
                            CategoryId = 1,
                            PageCount = 724,
                            PublishDate = new DateTime(1971, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tutunamayanlar"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Aldous Huxley",
                            CategoryId = 2,
                            PageCount = 272,
                            PublishDate = new DateTime(1932, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cesur Yeni Dünya"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilim Kurgu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Yazılım"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Psikoloji"
                        });
                });

            modelBuilder.Entity("LibraryApi.Models.Book", b =>
                {
                    b.HasOne("LibraryApi.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryApi.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
